module Termvas
  VERSION: String

  class Terminal
    def initialize: (?input: untyped, ?output: untyped, ?alt_screen: bool, ?tmux: bool, ?env: Hash[String, String]) -> void
    def size: () -> [Integer, Integer]
    def cell_size: () -> [Integer, Integer]
  end
end
